server:
  port: 8080
  servlet:
    context-path: /irrigation-service/api/v1

spring:
  application:
    name: automatic-irrigation-service

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  locations: classpath:/db/migration

logging:
  file:
    name: ./log/irrigation-global.log
