CREATE SEQUENCE IF NOT EXISTS LAND_SEQ INCREMENT 1 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS IRRIGATION_SEQ INCREMENT 1 START WITH 1;
CREATE SEQUENCE IF NOT EXISTS IRRIGATION_HISTORY_SEQ INCREMENT 1 START WITH 1;